#! /bin/sh
killall sxhkd
killall polybar
killall compton
killall unclutter

sxhkd &
compton &
dunst &
unclutter &
./.config/polybar/startall.sh
hsetroot -solid '#151515' &
xrdb .Xresources

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9
# bspc monitor eDP-1 -d 8 9
# bspc monitor HDMI-1 -d 1 2 3 4 5 6 7

bspc config border_width 1
bspc config window_gap   20

bspc config normal_border_color  "#1c1c1c"
bspc config focused_border_color "#2c2c2c"

bspc config presel_feedback_color "#5f5f87"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config focus_follows_pointer true
bspc config gapless_monocle       false

bspc config top_padding    0
bspc config left_padding   76
bspc config bottom_padding 0
bspc config right_padding  76

# rules
bspc rule -a feh state=floating
bspc rule -a URxvt state=pseudo_tiled center=true rectangle=550x350+0+0
bspc rule -a qjackctl state=floating center=true rectangle=750x500+0+0
bspc rule -a qutebrowser state=fullscreen
bspc rule -a firefox state=fullscreen
